spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:db/mysql/schema.sql
      data-locations: classpath:db/mysql/data.sql

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: dev-derby
  datasource:
    url: jdbc:derby:memory:userdb;create=true
    username: sa
    password:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:db/derby/schema.sql
      data-locations: classpath:db/derby/data.sql
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/userdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:db/mysql/schema.sql
      data-locations: classpath:db/mysql/data.sql

server:
  port: 8080