# version: '3'

services:
  wiremock:
    image: wiremock/wiremock:2.32.0
    ports:
      - "8080:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    command:
      - --verbose
      - --global-response-templating

volumes:
  mappings: